---

plugins:
  - jest
  - flowtype

env:
  node: true
  jest: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:flowtype/recommended'

parserOptions:
  ecmaVersion: 2017
  sourceType: module

rules:
  no-console: 0